### ISSUE TITLE
Not works with m.vk.com

### ISSUE THREAD

**Issue by byvlad** [biganfa/vk-auth#1]
Please, add support for m.vk.com links

**Comment by ivastly** [comment]
Could you please explain in detail what do you mean? The library just takes login & pass as input, not any links.

**Comment by byvlad** [comment]
For example: i want to view page http://m.vk.com/audio
But your script works only with http://vk.com/audio

**Comment by ivastly** [comment]
understood, i will look at it soon

**Comment by byvlad** [comment]
thanks 👍

**Comment by ivastly** [comment]
Hey @byvlad,

i have just run simple tests and the script does work with m.vk.com already. You just need to create different *Guzzle* client and pass *m.vk.com* as a base_uri to it. Just like it is done in the following code snippet (notice the 'base_uri' option value):

```
$mobileClient = new GuzzleHttp\Client([
    'base_uri' => 'http://m.vk.com',
    'timeout' => 10,
]);

/** @var \GuzzleHttp\Psr7\Response $mobileResponse */
$mobileResponse = $mobileClient->get('/audio', [
        'alow_redirects' => true,
        'cookies' => $jar
    ]);
```
