### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by Warchiefs** [biganfa/vk-auth#2]
When i try to install via composer - i have this:

[InvalidArgumentException]                                                                                                                       
  Could not find package biganfa/vk-auth at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by Deifinger** [comment]
@Warchiefs you can use this code in your composer.json for resolving problem:

`"repositories": [`
` {`
`"type": "package",`
            `"package": {`
               ` "name": "biganfa/vk-auth",`
                `"version": "v0.0.1",`
                `"source": {`
                   ` "url": "git@github.com:biganfa/vk-auth.git",`
                    `"type": "git",`
                    `"reference": "b0c57050419db3ff579637870fbeb159877cc593"`
               ` }`
           ` }`
       ` }`
  `  ],`

and than:

`"require": {
        "biganfa/vk-auth": "~0.0.1"
    },`

**Comment by ivastly** [comment]
i removed minimum-stability setting from composer.json, should be good now
